package com.of.music.storage.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.of.music.model.Imusic;

import com.of.music.storage.db.greendao.ImusicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imusicDaoConfig;

    private final ImusicDao imusicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imusicDaoConfig = daoConfigMap.get(ImusicDao.class).clone();
        imusicDaoConfig.initIdentityScope(type);

        imusicDao = new ImusicDao(imusicDaoConfig, this);

        registerDao(Imusic.class, imusicDao);
    }
    
    public void clear() {
        imusicDaoConfig.clearIdentityScope();
    }

    public ImusicDao getImusicDao() {
        return imusicDao;
    }

}
